### ISSUE TITLE
Interested in CoreSymbolication?

### ISSUE THREAD

**Issue by mattmassicotte** [packagesdev/unexpectedly#2]
Hello - this project is awesome!

I was blown away to see that you actually do the DWARF information parsing yourself. This must have been a huge amount of work.

For my own project (stacksift.io), I make extensive use of CoreSymbolication, which is unfortunately a private framework. It's very powerful, though slightly difficult to use for direct address lookup. While there are a few other open source CoreSymbolication implementations out there, I was considering opening up mine, as it contains both a C and Swift wrapper around the library. Does this sound like something you might be interested in?

**Comment by packagesdev** [comment]
Hi,

I've considered using one of the following solutions:
a. CoreSymbolication
b. atos or dwarfdump command line tools through a NSTask
c. lldb source code

I did not for the following reasons:
a. a quick look at the framework with class dump ended up being a disappointment. Also it's a private framework so subject to changes and I tried to limit the number of private APIs in this software.
b. the DWARF versions supported by these tools depend on the OS version or the installed Xcode version. On older OS versions, I was not getting the correct line numbers because of this. Also it's not optimized.
c. the source code for lldb is too big and handles too many cases that I don't need to support (I currently don't support all the tags). And this would require me to check the lldb repository for bug fixes.

There's another reason: when I begun writing my own code for this, I thought that supporting DWARF 3 would be enough and that the line numbers/source files info would be directly available. Silly me.

Thank you for the generous offer but, in the short term, I will keep using my code for the symbolication process as I'm now used to decipher the DWARF documentation and spending time executing the Line Number Programs step by step.

**Comment by mattmassicotte** [comment]
Thanks for taking the time to explain all this - these are great reasons! I had a feeling, given how much implementation you had that you put some serious thought into it.

I'm really looking forward to watching the project. Fantastic work!
